/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Equipment = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const FAQ = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const GymLocation = IDL.Record({
  'hours' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ActivityLevel = IDL.Variant({
  'active' : IDL.Null,
  'sedentary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Goal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const DietaryPreference = IDL.Variant({
  'vegan' : IDL.Null,
  'nonVegetarian' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'goal' : Goal,
  'weightKg' : IDL.Float64,
  'dietaryPreference' : DietaryPreference,
});
export const Workout = IDL.Record({
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'muscleGroup' : IDL.Text,
});
export const Meal = IDL.Record({
  'carbs' : IDL.Nat,
  'fats' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'protein' : IDL.Nat,
});
export const DailyMealPlan = IDL.Record({
  'totalCarbs' : IDL.Nat,
  'breakfast' : Meal,
  'totalFats' : IDL.Nat,
  'totalCalories' : IDL.Nat,
  'lunch' : Meal,
  'snacks' : IDL.Vec(Meal),
  'totalProtein' : IDL.Nat,
  'dinner' : Meal,
});

export const idlService = IDL.Service({
  'addEquipment' : IDL.Func([Equipment], [], []),
  'addFAQ' : IDL.Func([FAQ], [], []),
  'addGymLocation' : IDL.Func([GymLocation], [], []),
  'addMealPlan' : IDL.Func([UserProfile], [], []),
  'addWorkout' : IDL.Func([Workout], [], []),
  'getEquipment' : IDL.Func([IDL.Text], [Equipment], ['query']),
  'getFAQ' : IDL.Func([IDL.Text], [FAQ], ['query']),
  'getGymLocation' : IDL.Func([IDL.Text], [GymLocation], ['query']),
  'getMealPlan' : IDL.Func([IDL.Text], [DailyMealPlan], ['query']),
  'getWorkout' : IDL.Func([IDL.Text], [Workout], ['query']),
  'listEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'listFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'listGymLocations' : IDL.Func([], [IDL.Vec(GymLocation)], ['query']),
  'listWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Equipment = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const FAQ = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const GymLocation = IDL.Record({
    'hours' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ActivityLevel = IDL.Variant({
    'active' : IDL.Null,
    'sedentary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const DietaryPreference = IDL.Variant({
    'vegan' : IDL.Null,
    'nonVegetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'goal' : Goal,
    'weightKg' : IDL.Float64,
    'dietaryPreference' : DietaryPreference,
  });
  const Workout = IDL.Record({
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'muscleGroup' : IDL.Text,
  });
  const Meal = IDL.Record({
    'carbs' : IDL.Nat,
    'fats' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const DailyMealPlan = IDL.Record({
    'totalCarbs' : IDL.Nat,
    'breakfast' : Meal,
    'totalFats' : IDL.Nat,
    'totalCalories' : IDL.Nat,
    'lunch' : Meal,
    'snacks' : IDL.Vec(Meal),
    'totalProtein' : IDL.Nat,
    'dinner' : Meal,
  });
  
  return IDL.Service({
    'addEquipment' : IDL.Func([Equipment], [], []),
    'addFAQ' : IDL.Func([FAQ], [], []),
    'addGymLocation' : IDL.Func([GymLocation], [], []),
    'addMealPlan' : IDL.Func([UserProfile], [], []),
    'addWorkout' : IDL.Func([Workout], [], []),
    'getEquipment' : IDL.Func([IDL.Text], [Equipment], ['query']),
    'getFAQ' : IDL.Func([IDL.Text], [FAQ], ['query']),
    'getGymLocation' : IDL.Func([IDL.Text], [GymLocation], ['query']),
    'getMealPlan' : IDL.Func([IDL.Text], [DailyMealPlan], ['query']),
    'getWorkout' : IDL.Func([IDL.Text], [Workout], ['query']),
    'listEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'listFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'listGymLocations' : IDL.Func([], [IDL.Vec(GymLocation)], ['query']),
    'listWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };