/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'active' : null } |
  { 'sedentary' : null } |
  { 'moderate' : null };
export interface DailyMealPlan {
  'totalCarbs' : bigint,
  'breakfast' : Meal,
  'totalFats' : bigint,
  'totalCalories' : bigint,
  'lunch' : Meal,
  'snacks' : Array<Meal>,
  'totalProtein' : bigint,
  'dinner' : Meal,
}
export type DietaryPreference = { 'vegan' : null } |
  { 'nonVegetarian' : null } |
  { 'vegetarian' : null };
export interface Equipment {
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface FAQ {
  'question' : string,
  'answer' : string,
  'category' : string,
}
export type Goal = { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null };
export interface GymLocation {
  'hours' : string,
  'city' : string,
  'name' : string,
  'amenities' : Array<string>,
  'address' : string,
  'phone' : string,
}
export interface Meal {
  'carbs' : bigint,
  'fats' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'protein' : bigint,
}
export interface UserProfile {
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'goal' : Goal,
  'weightKg' : number,
  'dietaryPreference' : DietaryPreference,
}
export interface Workout {
  'difficulty' : string,
  'name' : string,
  'description' : string,
  'steps' : Array<string>,
  'muscleGroup' : string,
}
export interface _SERVICE {
  'addEquipment' : ActorMethod<[Equipment], undefined>,
  'addFAQ' : ActorMethod<[FAQ], undefined>,
  'addGymLocation' : ActorMethod<[GymLocation], undefined>,
  'addMealPlan' : ActorMethod<[UserProfile], undefined>,
  'addWorkout' : ActorMethod<[Workout], undefined>,
  'getEquipment' : ActorMethod<[string], Equipment>,
  'getFAQ' : ActorMethod<[string], FAQ>,
  'getGymLocation' : ActorMethod<[string], GymLocation>,
  'getMealPlan' : ActorMethod<[string], DailyMealPlan>,
  'getWorkout' : ActorMethod<[string], Workout>,
  'listEquipment' : ActorMethod<[], Array<Equipment>>,
  'listFAQs' : ActorMethod<[], Array<FAQ>>,
  'listGymLocations' : ActorMethod<[], Array<GymLocation>>,
  'listWorkouts' : ActorMethod<[], Array<Workout>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];