/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    carbs: bigint;
    fats: bigint;
    calories: bigint;
    name: string;
    description: string;
    protein: bigint;
}
export interface FAQ {
    question: string;
    answer: string;
    category: string;
}
export interface GymLocation {
    hours: string;
    city: string;
    name: string;
    amenities: Array<string>;
    address: string;
    phone: string;
}
export interface Equipment {
    name: string;
    description: string;
    category: string;
    price: bigint;
}
export interface DailyMealPlan {
    totalCarbs: bigint;
    breakfast: Meal;
    totalFats: bigint;
    totalCalories: bigint;
    lunch: Meal;
    snacks: Array<Meal>;
    totalProtein: bigint;
    dinner: Meal;
}
export interface Workout {
    difficulty: string;
    name: string;
    description: string;
    steps: Array<string>;
    muscleGroup: string;
}
export interface UserProfile {
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    weightKg: number;
    dietaryPreference: DietaryPreference;
}
export enum ActivityLevel {
    active = "active",
    sedentary = "sedentary",
    moderate = "moderate"
}
export enum DietaryPreference {
    vegan = "vegan",
    nonVegetarian = "nonVegetarian",
    vegetarian = "vegetarian"
}
export enum Goal {
    weightLoss = "weightLoss",
    muscleGain = "muscleGain",
    maintenance = "maintenance"
}
export interface backendInterface {
    addEquipment(equipment: Equipment): Promise<void>;
    addFAQ(faq: FAQ): Promise<void>;
    addGymLocation(location: GymLocation): Promise<void>;
    addMealPlan(profile: UserProfile): Promise<void>;
    addWorkout(workout: Workout): Promise<void>;
    getEquipment(name: string): Promise<Equipment>;
    getFAQ(question: string): Promise<FAQ>;
    getGymLocation(name: string): Promise<GymLocation>;
    getMealPlan(key: string): Promise<DailyMealPlan>;
    getWorkout(name: string): Promise<Workout>;
    listEquipment(): Promise<Array<Equipment>>;
    listFAQs(): Promise<Array<FAQ>>;
    listGymLocations(): Promise<Array<GymLocation>>;
    listWorkouts(): Promise<Array<Workout>>;
}
import type { ActivityLevel as _ActivityLevel, DietaryPreference as _DietaryPreference, Goal as _Goal, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEquipment(arg0: Equipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipment(arg0);
            return result;
        }
    }
    async addFAQ(arg0: FAQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0);
            return result;
        }
    }
    async addGymLocation(arg0: GymLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGymLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGymLocation(arg0);
            return result;
        }
    }
    async addMealPlan(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMealPlan(to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMealPlan(to_candid_UserProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWorkout(arg0: Workout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkout(arg0);
            return result;
        }
    }
    async getEquipment(arg0: string): Promise<Equipment> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipment(arg0);
            return result;
        }
    }
    async getFAQ(arg0: string): Promise<FAQ> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQ(arg0);
            return result;
        }
    }
    async getGymLocation(arg0: string): Promise<GymLocation> {
        if (this.processError) {
            try {
                const result = await this.actor.getGymLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGymLocation(arg0);
            return result;
        }
    }
    async getMealPlan(arg0: string): Promise<DailyMealPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan(arg0);
            return result;
        }
    }
    async getWorkout(arg0: string): Promise<Workout> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkout(arg0);
            return result;
        }
    }
    async listEquipment(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEquipment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEquipment();
            return result;
        }
    }
    async listFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFAQs();
            return result;
        }
    }
    async listGymLocations(): Promise<Array<GymLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGymLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGymLocations();
            return result;
        }
    }
    async listWorkouts(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkouts();
            return result;
        }
    }
}
function to_candid_ActivityLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryPreference_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): _DietaryPreference {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityLevel: ActivityLevel;
    heightCm: number;
    goal: Goal;
    weightKg: number;
    dietaryPreference: DietaryPreference;
}): {
    activityLevel: _ActivityLevel;
    heightCm: number;
    goal: _Goal;
    weightKg: number;
    dietaryPreference: _DietaryPreference;
} {
    return {
        activityLevel: to_candid_ActivityLevel_n3(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        goal: to_candid_Goal_n5(_uploadFile, _downloadFile, value.goal),
        weightKg: value.weightKg,
        dietaryPreference: to_candid_DietaryPreference_n7(_uploadFile, _downloadFile, value.dietaryPreference)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    active: null;
} | {
    sedentary: null;
} | {
    moderate: null;
} {
    return value == ActivityLevel.active ? {
        active: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} {
    return value == Goal.weightLoss ? {
        weightLoss: null
    } : value == Goal.muscleGain ? {
        muscleGain: null
    } : value == Goal.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): {
    vegan: null;
} | {
    nonVegetarian: null;
} | {
    vegetarian: null;
} {
    return value == DietaryPreference.vegan ? {
        vegan: null
    } : value == DietaryPreference.nonVegetarian ? {
        nonVegetarian: null
    } : value == DietaryPreference.vegetarian ? {
        vegetarian: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
